import LoadingSpinnerComponent from '../components/loading-spinner';
import PokemonDetailComponent from '../components/pokemon-detail';
import PokemonListComponent from '../components/pokemon-list';
import { PokemonList, PokemonListItem } from '../shared/entities/pokemon.entity';
import { pokemonService } from '../shared/services/pokemon.service';
import Head from 'next/head';
import { useEffect, useState } from 'react';

import type { NextPage } from 'next';
const Home: NextPage = () => {
  const [pokemonList, setPokemonList] = useState<PokemonList>();
  const [selectedPokemon, setSelectedPokemon] = useState<PokemonListItem>();
  const [favoritePokemonName, setFavoritePokemonName] = useState<string>('');

  const [status, setStatus] = useState<'idle' | 'pending' | 'resolved' | 'rejected'>('idle');

  useEffect(() => {
    fetchPokemon();
  }, []);

  useEffect(() => {
    syncFavoritePokemonWithLocalStorage();
  }, [favoritePokemonName]);

  function fetchPokemon(): void {
    setStatus('pending');

    pokemonService
      .getAll()
      .then(result => fetchPokemonSuccessfull(result.data))
      .catch(() => fetchPokemonFailed());
  }

  function fetchPokemonSuccessfull(result: PokemonList): void {
    setPokemonList(result);
    setSelectedPokemon(result.results[0]);
    setStatus('resolved');
  }

  function fetchPokemonFailed(): void {
    setStatus('rejected');
  }

  function syncFavoritePokemonWithLocalStorage(): void {
    const localStorageValue = window.localStorage.getItem('favorite-pokemon');

    if (!favoritePokemonName && localStorageValue) {
      setFavoritePokemonName(localStorageValue);
    } else {
      window.localStorage.setItem('favorite-pokemon', favoritePokemonName);
    }
  }

  return (
    <div>
      <Head>
        <title>WeGroup FE assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {status === 'pending' && <LoadingSpinnerComponent></LoadingSpinnerComponent>}

        {status === 'resolved' && (
          <div className="pokemon-container">
            <PokemonListComponent
              pokemonList={pokemonList!}
              selectedPokemon={selectedPokemon!}
              setSelectedPokemon={setSelectedPokemon}
              favoritePokemonName={favoritePokemonName}
            ></PokemonListComponent>
            <PokemonDetailComponent
              selectedPokemon={selectedPokemon!}
              favoritePokemonName={favoritePokemonName!}
              setFavoritePokemonName={setFavoritePokemonName}
            ></PokemonDetailComponent>
          </div>
        )}

        {status === 'rejected' && (
          <div>
            <h2>Failed to fetch pokemon data</h2>
            <p>Please try again later</p>
          </div>
        )}
      </main>
    </div>
  );
};

export default Home;
